name: build

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

jobs:
  main-linux:
   uses: asottile/workflows/.github/workflows/tox.yml@v1.0.0
   with:
      env: '["py37", "py38", "py39", "py310"]'
      os: ubuntu-latest
